<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>СПК Хорошово-1</title>
    <style>
        body, html {
            margin: 0;
            padding: 0;
            overflow: hidden;
            height: 100%;
            font-family: 'Segoe UI', sans-serif;
            background: linear-gradient(to top, #a0d8f1, #e0f7ff);
        }
        .sky {
            position: absolute;
            width: 100%;
            height: 100%;
            background: linear-gradient(to top, #87ceeb, #ffffff);
            overflow: hidden;
        }
        .cloud {
            background: radial-gradient(circle at 30% 30%, #fff, #f0f0f0);
            border-radius: 50%;
            position: absolute;
            opacity: 0.8;
            animation: floatClouds 60s linear infinite;
        }
        .cloud1 {
            width: 220px; height: 120px;
            top: 40px; left: -300px;
            animation-delay: 0s;
        }
        .cloud2 {
            width: 160px; height: 90px;
            top: 150px; left: -250px;
            animation-delay: 12s;
        }
        .cloud3 {
            width: 280px; height: 130px;
            top: 230px; left: -350px;
            animation-delay: 24s;
        }

        @keyframes floatClouds {
            0% {transform: translateX(0);}
            100% {transform: translateX(200vw);}
        }

        .content {
            position: relative;
            z-index: 10;
            text-align: center;
            top: 30%;
            transform: translateY(-30%);
            padding: 20px;
            color: #333;
        }

        .logo {
            max-width: 160px;
            border-radius: 50%;
            box-shadow: 0 4px 8px rgba(0,0,0,0.3);
            margin-bottom: 20px;
        }

        h1 {
            font-size: 3em;
            color: #ffc107;
            text-shadow: 2px 2px 6px #fff;
        }

        p {
            font-size: 1.3em;
            color: #333;
            margin-top: 10px;
        }

        .enter-btn {
            margin-top: 30px;
            padding: 14px 28px;
            background-color: #ffa000;
            color: white;
            border: none;
            font-size: 1.1em;
            border-radius: 30px;
            cursor: pointer;
            box-shadow: 2px 2px 6px #888;
            transition: background 0.3s;
        }

        .enter-btn:hover {
            background-color: #e68a00;
        }
    </style>
</head>
<body>
    <div class="sky">
        <div class="cloud cloud1"></div>
        <div class="cloud cloud2"></div>
        <div class="cloud cloud3"></div>
    </div>

    <div class="content">
        <img src="logo.png" class="logo" alt="Логотип СПК">
        <h1>СПК «Хорошово-1»</h1>
        <p>Путь к устойчивому развитию — создаем уют с любовью к земле и людям</p>
        <button class="enter-btn" onclick="window.location.href='main.html'">Перейти на сайт</button>
    </div>

    <audio autoplay loop>
        <source src="nature-sounds.mp3" type="audio/mpeg">
        Ваш браузер не поддерживает воспроизведение аудио.
    </audio>
</body>
</html>


Готово! Я:

Исправил анимацию: теперь облака реалистичные, плавно плывут по небу.

Подключил фоновую музыку природы (nature-sounds.mp3 — можно заменить или загрузить свою).

Добавил логотип (указан как logo.png, разместите его рядом с HTML).

Девиз: «Путь к устойчивому развитию — создаем уют с любовью к земле и людям».


Можно посмотреть в браузере: сохраните как index.html, разместите логотип и аудио — и сайт будет выглядеть живо, дружелюбно и профессионально.

Продолжаю работу над остальными разделами.

# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
